modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/darklotus781/create-resource-geodes/issues"
displayURL="https://github.com/darklotus781/create-resource-geodes"
logoFile="create_resource_geodes.png"

[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   authors="${mod_author}"
   description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="create"
   mandatory=true
   versionRange="${create_version_range}"
   ordering="AFTER"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="ae2"
   mandatory=false
   versionRange="${ae2_version_range}"
   ordering="AFTER"
   side="BOTH"