package com.lithiumcraft.createresourcegeodes.block;

import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

public class CrimsiteCatalystBlock extends CatalystBlock {

    /**
     * Define the block generated by the Catalyst
     */
    public static final Block Crimsite = Registry.BLOCK.get(new ResourceLocation("create", "crimsite")); // This is different in 1.20.1

    public CrimsiteCatalystBlock(Properties pProperties) {
        super(pProperties);
    }
}
